language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - ENV=production yarn test
  - yarn build-prod
  - yarn docker-run-test
  - yarn docker-stop-test

deploy:
  skip_cleanup: true
  provider: script
  script: bash src/build/heroku_release.sh
  on:
    branch: master
